### PR TITLE
Fix missing scoutd user. Version bump.

### PR DESCRIPTION
**Pull request by heyryanw**
The scoutd user should preferably created on package install (doesn't happen with Debian package, not sure about other platforms). This means manual installs of the package won't work either. Version bump as well.

### CODE REVIEW

**Comment by dlanderson** [comment]
Hrm, the scoutd user should be created by the package on installation. I can check this out more on Monday - what version of Debian are you running @heyryanw ?

**Comment by heyryanw** [comment]
Tried on 7 & 8. Both are missing user creation. You should see an error on install about not being able to chown the /var/lib/scoutd directory due to the scoutd user not existing. Maybe just an ordering issue with user creation before chown.

**Comment by dlanderson** [comment]
Thanks, Ryan. I've confirmed the package installation is creating the scoutd user/groups as expected for both wheezy and jessie. We'll check to see why the cookbook is borked.

**Comment by composit** [comment]
Hey @heyryanw -

It works for me on Debian 7. One thing I noticed is that if you [don't supply an account_key] (https://github.com/scoutapp/scout_cookbooks/blob/master/recipes/default.rb#L36) (node[:scout][:account_key]), it skips the scoutd package install and continues on to create the other directories, etc. The scoutd package install is where the scoutd user is created.

In the missing account_key scenario, a message is logged regarding the missing account_key, but then it later fails because of the missing scoutd user.

I made a [change] (https://github.com/scoutapp/scout_cookbooks/commit/5d7a437f4a2f1df8600f67795a76e26a1de9fecf#diff-55bf87238c9b8af164c5133a60721f12) so that the missing account key raises an exception and makes it clearer what the actual error is. Can you give the updated script a try and let me know if it works for you?

**Comment by heyryanw** [comment]
We've always had account_key attached to the default attributes in the cookbook, so I don't think that was the problem we were having. We were getting errors for the scoutd user not existing to chown /var/lib/scoutd on package install, which means the account_key existed already in order for the package install to happen.

I reverted back to not handling the user in our override cookbook, and everything seems to work now, so no issue anymore :)

Is there no public repo to view package build files?

**Pull request closed without merging**
